# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "iamsachin-terraform-bucket"
    dynamodb_table = "terraform-lock"
    encrypt        = true
    key            = "environments/test/eks/cgaas-eks-cluster/terraform.tfstate"
    region         = "us-east-1"
  }
}
